export const servicePages = {
  "saas-web-apps": {
    name: "SaaS & Web Apps",
    number: "02",
    title: "Make the complex work simply.",
    lead: "I build web applications for teams whose important workflows need more than a website: customer portals, dashboards, internal tools, and connected systems.",
    offer: "Scoped web application",
    fitTitle: "For work that needs a real product.",
    fit: "This fits when people need to sign in, manage information, complete a workflow, or use software that connects to the rest of your business. We start with the people using it and the job it needs to do.",
    includedTitle: "Define the workflow. Build the system.",
    included: "We agree on the users, core workflows, integrations, and handoff before implementation. The build is shaped around that scope.",
    deliverables: ["Product and technical scope", "Agreed application workflows", "APIs and integrations if scoped", "Working handoff and known constraints"],
    scopeNote: "Hosting, ongoing maintenance, and later features are discussed as part of scope or quoted separately.",
    steps: [
      { name: "Discover", description: "Map the people, current workflow, and points where the existing process breaks down." },
      { name: "Scope", description: "Agree on the first useful set of workflows, integrations, responsibilities, and quote." },
      { name: "Build", description: "Implement the agreed application and review how its core workflows behave." },
      { name: "Handoff", description: "Walk through the working system, its code, and any known constraints." },
    ],
    faqs: [
      { question: "Can you build on an existing app?", answer: "Yes. I can review an existing codebase and propose a scoped improvement or new feature after understanding its current state." },
      { question: "Do you handle integrations?", answer: "Integrations can be included when the systems, access, and expected behavior are defined during scoping." },
      { question: "Is UI design included?", answer: "Design needs are discussed during scoping. If you have designs, I can build from them; any design work must be agreed separately." },
      { question: "How is the price decided?", answer: "I quote after we agree on the workflows, integrations, and deliverables. There is no published starting price for this service yet." },
      { question: "What happens after handoff?", answer: "We can scope maintenance, improvements, or new features separately." },
    ],
    closeTitle: "Tell me where the workflow gets stuck.",
    close: "A rough brief and a look at the current process are enough to start a conversation.",
  },
  "ai-products-features": {
    name: "AI Products & Features",
    number: "03",
    title: "Give AI a useful job to do.",
    lead: "I help turn an AI idea into a defined product feature or workflow that people can understand, use, and review.",
    offer: "Scoped AI feature or product",
    fitTitle: "Start with the decision or task.",
    fit: "This fits when a team has a specific task that could benefit from language models, search over its knowledge, or an assisted workflow. We define what the system should do, what it should show, and where a person stays in control.",
    includedTitle: "A use case before a model choice.",
    included: "The scope covers the user workflow, relevant data sources, integration points, and how to check useful and incorrect results. The exact implementation follows from those decisions.",
    deliverables: ["Use-case and workflow definition", "Agreed data and integration boundaries", "Scoped feature or product build", "Review path for uncertain outputs"],
    scopeNote: "Model costs, third-party services, data access, and ongoing operation are clarified in the quote. No accuracy or automation outcome is assumed in advance.",
    steps: [
      { name: "Discover", description: "Understand the task, the people doing it, and the information they need." },
      { name: "Scope", description: "Choose the workflow, data boundaries, review points, and success checks." },
      { name: "Build", description: "Implement the agreed feature and connect it to the right product surface." },
      { name: "Review", description: "Walk through useful cases, failure cases, and the limits of the shipped scope." },
    ],
    faqs: [
      { question: "Do I need to know which model to use?", answer: "No. We start with the task and constraints, then choose an approach during scoping." },
      { question: "Can this work inside an existing product?", answer: "Yes. I can scope an AI feature within an existing product after reviewing its architecture and integration needs." },
      { question: "Will the system act without a person reviewing it?", answer: "That depends on the task and its consequences. We define review and approval points during scoping rather than assume full automation." },
      { question: "How is pricing handled?", answer: "I quote the build after defining the workflow, data access, integrations, and deliverables. Third-party usage costs are discussed separately." },
      { question: "Can we improve it after launch?", answer: "Yes. Changes and ongoing evaluation can be scoped and quoted separately." },
    ],
    closeTitle: "Bring the task, not a model name.",
    close: "Tell me what people need help doing and where the current workflow falls short.",
  },
  "mobile-apps": {
    name: "Mobile Apps",
    number: "04",
    title: "Put the product in their hands.",
    lead: "I build scoped mobile experiences, with the platform, backend, and integrations chosen for the agreed workflow.",
    offer: "Scoped mobile application",
    fitTitle: "For a workflow that belongs on a phone.",
    fit: "A mobile app makes sense when the product needs to be close to the user, used on the move, or connected to device capabilities. We decide what belongs in the first version before choosing the build approach.",
    includedTitle: "The app and the system behind it.",
    included: "We define the key screens, user journeys, backend needs, and integrations together. The scope determines what is built and what is needed to release it.",
    deliverables: ["Core mobile journeys", "Agreed backend and API work", "Authentication or payments if scoped", "Build handoff and release requirements"],
    scopeNote: "UI design, store accounts, submission responsibilities, third-party costs, and ongoing support are agreed during scoping. Store approval is controlled by the platform.",
    steps: [
      { name: "Discover", description: "Understand who uses the app, where they use it, and the main job it should do." },
      { name: "Scope", description: "Agree on the first journeys, design inputs, backend needs, release path, and quote." },
      { name: "Build", description: "Implement the agreed app and connected services, then review the core journeys." },
      { name: "Handoff", description: "Provide the agreed build and code with release steps and known constraints documented." },
    ],
    faqs: [
      { question: "Will it work on iOS and Android?", answer: "That is decided during scoping. I can plan a cross-platform build when it fits the product and requirements." },
      { question: "Do I need designs?", answer: "We establish design inputs before the build. If you already have UI designs, I can work from them; design work is agreed separately." },
      { question: "Can the app use my existing backend?", answer: "I can review the existing APIs and account for integration in the scope if they support the required journeys." },
      { question: "Is app-store publication included?", answer: "Submission responsibilities and store-account access are agreed during scoping. The stores make their own approval decisions." },
      { question: "How much will it cost?", answer: "I quote after we define the platforms, screens, backend work, integrations, and release responsibilities. There is no published starting price for this service yet." },
    ],
    closeTitle: "Show me the mobile moment.",
    close: "Tell me what someone needs to do on their phone and what exists today.",
  },
} as const;

export type DraftServiceSlug = keyof typeof servicePages;
